ai_phrases = [
    "It's important to note",
    "In conclusion, we can say",
    "One might argue",
    "This suggests",
    "The data indicates",
    "On the other hand",
    "Given these facts",
    "From a different perspective",
    "As a result of this",
    "Therefore, it is clear",
    "According to recent studies",
    "It has been proven",
    "In light of this information",
    "While this may be true",
    "This could potentially mean",
    "Interestingly, research has shown",
    "Based on these findings",
    "It is widely believed",
    "Taking into account all these factors",
    "However, this viewpoint is not universally accepted",
    "From the aforementioned points, it is evident",
    "To delve deeper into this topic",
    "Additionally, it's worth considering",
    "A key point to remember is",
    "Furthermore, evidence suggests",
    "Another point worth noting is",
    "In essence, this implies",
    "In comparison to this",
    "Conversely, others argue",
    "Despite these arguments",
    "Looking at the bigger picture",
    "To put it simply",
    "This brings us to the conclusion",
    "Significantly, it has been observed",
    "It should be emphasized",
    "Hence, it can be inferred",
    "For the reasons discussed above",
    "It is evident from the discussion",
    "Summing up, it can be said",
    "An alternative viewpoint suggests",
    "The implications of this are",
    "Upon closer examination",
    "Contrary to popular belief",
    "From this perspective, one can deduce",
    "With this in mind",
    "Drawing upon the evidence",
    "This leads us to believe",
    "Correspondingly, we can see",
    "Building on this point",
    "Given this perspective"
]
