ai_phrases = [
    "It's important to note",
    "In conclusion, we can say",
    "One might argue",
    "This suggests",
    "The data indicates",
    "On the other hand",
    "Given these facts",
    "From a different perspective",
    "As a result of this",
    "Therefore, it is clear",
    "According to recent studies",
    "It has been proven",
    "In light of this information",
    "While this may be true",
    "This could potentially mean",
    "Interestingly, research has shown",
    "Based on these findings",
    "It is widely believed",
    "Taking into account all these factors",
    "However, this viewpoint is not universally accepted",
    "From the aforementioned points, it is evident",
    "To delve deeper into this topic",
    "Additionally, it's worth considering",
    "A key point to remember is",
    "Furthermore, evidence suggests",
    "Another point worth noting is",
    "In essence, this implies",
    "In comparison to this",
    "Conversely, others argue",
    "Despite these arguments",
    "Looking at the bigger picture",
    "To put it simply",
    "This brings us to the conclusion",
    "Significantly, it has been observed",
    "It should be emphasized",
    "Hence, it can be inferred",
    "For the reasons discussed above",
    "It is evident from the discussion",
    "Summing up, it can be said",
    "An alternative viewpoint suggests",
    "The implications of this are",
    "Upon closer examination",
    "Contrary to popular belief",
    "From this perspective, one can deduce",
    "With this in mind",
    "Drawing upon the evidence",
    "This leads us to believe",
    "Correspondingly, we can see",
    "Building on this point",
    "Given this perspective"
]

clickbait_phrases = [
    "A shocking revelation",
    "Believe it or not",
    "But that's not all",
    "Discover the truth behind",
    "Don't miss out",
    "Experts are stunned",
    "Find out why",
    "Get it before it's gone",
    "Here's what happened next",
    "Incredible results",
    "It's a game changer",
    "It's not what you think",
    "Just revealed",
    "Little known ways to",
    "Mind-blowing facts about",
    "No one saw this coming",
    "Once in a lifetime opportunity",
    "People can't believe",
    "Proven methods for",
    "Secrets they don't want you to know",
    "See it to believe it",
    "Shocking results",
    "Stop everything and read this",
    "Stunning transformation",
    "Surprising facts about",
    "This could be you",
    "This is what they found",
    "This will change your life",
    "Top secrets revealed",
    "Unbelievable story",
    "What they discovered will amaze you",
    "What they won't tell you",
    "What you've been missing out on",
    "Will blow your mind",
    "You won't believe",
    "You won't believe what happens next",
    "You'll never guess",
    "You'll never guess what happened",
    "You'll never look at it the same way",
    "You'll be shocked to learn",
    "You're doing it all wrong",
    "Your life will never be the same",
    "This little trick",
    "The most amazing story ever",
    "Insider reveals",
    "Must see",
    "Can't deny",
    "This unexpected twist",
    "Exposes the truth",
    "This one simple thing",
    "The hidden danger"
]
